環境構築
funrei-co/first-project pull request #3
Opened 2024-07-01 04:31 UTC by s-sasa-s

golang、Next.js、mysqlをdockerで環境構築するための設定

2024-07-01 07:15 UTC, shikamasaki requested changes

2024-07-01 07:15 UTC, shikamasaki commented on db/data/#ib_16384_0.dblwr
/db/data配下は全部Ignoreしてください

2024-07-01 07:15 UTC, shikamasaki commented on db/Dockerfile
> +FROM mysql:oraclelinux9
これ使ってるLinuxが微妙だから選択し直して

2024-07-01 07:15 UTC, shikamasaki commented on docker-compose.yml
> +      - ./next.js:/app
ファイル名がよくない
`.`をファイル名に置くと呼び出すときにエラーが起きやすい

2024-07-01 07:15 UTC, shikamasaki commented on docker-compose.yml
> +    container_name: MysqlDataBase
命名規則もうちょっとセンス出して

2024-07-01 07:15 UTC, shikamasaki commented on docker-compose.yml
> +  mysql :
謎のスペース

2024-07-01 07:15 UTC, shikamasaki commented on docker-compose.yml
> +    image: node:lts-slim
これノードのVerなんぼになるの？

2024-07-01 07:15 UTC, shikamasaki commented on docker-compose.yml
> +      - ./goproject:/app
フォルダの命名規則ちょっとダサいかも

2024-07-01 07:15 UTC, shikamasaki commented on docker-compose.yml
> +    build: .
こっちにもimage書いて明示化して

2024-07-01 07:15 UTC, shikamasaki commented on db/Dockerfile
> +RUN sed -e 's/^ *user *= *mysql$/user = root/' -i /db/my.cnf
これをやる意味がよくわからない

2024-07-01 07:15 UTC, shikamasaki commented on docker-compose.yml
> +    tty: true
フロントエンド、バックエンド、Mysqlで分けなくてもいいから一つのnetworks作って
https://docs.docker.jp/compose/networking.html#compose-speficy-custom-netowrks

2024-07-03 14:32 UTC, s-sasa-s commented on db/data/#ib_16384_0.dblwr
. dockerignoreを作成しました。

2024-07-03 14:33 UTC, s-sasa-s commented on db/Dockerfile
> +FROM mysql:oraclelinux9
mysql:oracleに変更しました。

2024-07-03 14:33 UTC, s-sasa-s commented on docker-compose.yml
> +      - ./next.js:/app
jsに変更しました。

2024-07-03 14:34 UTC, s-sasa-s commented on docker-compose.yml
> +    container_name: MysqlDataBase
container_name:sqldevelopに変更しました。

2024-07-03 14:34 UTC, s-sasa-s commented on docker-compose.yml
> +  mysql :
mysql:に変更しました。[90ae976](https://github.com/funrei-co/first-project/commit/90ae976518ea3f04650d857fcba104d929449ff8)

2024-07-03 14:35 UTC, s-sasa-s commented on docker-compose.yml
> +    image: node:lts-slim
node:22.3.0に変更したため、verは22.3.0になります。

2024-07-03 14:36 UTC, s-sasa-s commented on docker-compose.yml
> +      - ./goproject:/app
goに変更しました。

2024-07-03 14:36 UTC, s-sasa-s commented on docker-compose.yml
> +    build: .
image: mysql:oracleを追記しました。

2024-07-03 14:37 UTC, s-sasa-s commented on db/Dockerfile
> +RUN sed -e 's/^ *user *= *mysql$/user = root/' -i /db/my.cnf
記載を無くしました。

2024-07-03 14:37 UTC, s-sasa-s commented on docker-compose.yml
> +    tty: true
networksを作成しました。

2024-07-03 16:11 UTC, shikamasaki commented on db/Dockerfile
> +FROM mysql:oracle
これを指定してほしい。
これだけの記述なら、Dockerfile用意する必要なし。
https://hub.docker.com/layers/library/mysql/8.4.1/images/sha256-e24bd134ee2ed1538953b9d16f1bc4ecfd3a09af42728d2d780b930c61669610?context=explore

2024-07-03 16:22 UTC, shikamasaki requested changes

2024-07-03 16:22 UTC, shikamasaki commented on docker-compose.yml
> +      MYSQL_ROOT_PASSWORD: rootPass
`MYSQL_ALLOW_EMPTY_PASSWORD: yes`を使って消す

2024-07-03 16:22 UTC, shikamasaki commented on docker-compose.yml
> +      MYSQL_PASSWORD: chatpass001
消す

2024-07-03 16:22 UTC, shikamasaki commented on docker-compose.yml
> +   name: api_network
```
networks:
  chat-service:
    external : true
```

2024-07-03 16:22 UTC, shikamasaki commented on docker-compose.yml
> +      - internal
`- chat-service`

2024-07-03 16:22 UTC, shikamasaki commented on docker-compose.yml
> +      - external
`- chat-service`

2024-07-03 16:22 UTC, shikamasaki commented on docker-compose.yml
> +      - external
`- chat-service`

2024-07-03 16:25 UTC, shikamasaki commented on Dockerfile
> +WORKDIR /go
せめて/backendとかにして

2024-07-03 16:25 UTC, shikamasaki commented on docker-compose.yml
> +      - ./go:/app
名前

2024-07-03 16:25 UTC, shikamasaki commented on docker-compose.yml
> +      - ./js:/app
/frontend

2024-07-03 17:15 UTC, shikamasaki commented on docker-compose.yml
> +
謎の改行

2024-07-03 18:08 UTC, shikamasaki approved these changes

2024-07-03 18:09 UTC, merged